"""Add automation tables

Revision ID: df62a09f5c08
Revises: bc4534826873
Create Date: 2025-09-19 10:31:35.558937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df62a09f5c08'
down_revision = 'bc4534826873'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index('idx_automation_config_key', 'automation_config', ['config_key'], unique=True)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('applications_discovered', sa.Integer(), nullable=True),
    sa.Column('applications_processed', sa.Integer(), nullable=True),
    sa.Column('companies_matched', sa.Integer(), nullable=True),
    sa.Column('companies_enriched', sa.Integer(), nullable=True),
    sa.Column('new_companies_created', sa.Integer(), nullable=True),
    sa.Column('new_officers_created', sa.Integer(), nullable=True),
    sa.Column('contacts_enriched', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('boroughs_processed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('processing_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_automation_run_completed', 'automation_runs', ['completed_at'], unique=False)
    op.create_index('idx_automation_run_started', 'automation_runs', ['started_at'], unique=False)
    op.create_index('idx_automation_run_status', 'automation_runs', ['status'], unique=False)
    op.create_index('idx_automation_run_type', 'automation_runs', ['run_type'], unique=False)
    op.create_table('automation_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('job_config', sa.JSON(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('next_execution', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_automation_schedule_enabled', 'automation_schedules', ['is_enabled'], unique=False)
    op.create_index('idx_automation_schedule_job_id', 'automation_schedules', ['job_id'], unique=True)
    op.create_index('idx_automation_schedule_next', 'automation_schedules', ['next_execution'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_automation_schedule_next', table_name='automation_schedules')
    op.drop_index('idx_automation_schedule_job_id', table_name='automation_schedules')
    op.drop_index('idx_automation_schedule_enabled', table_name='automation_schedules')
    op.drop_table('automation_schedules')
    op.drop_index('idx_automation_run_type', table_name='automation_runs')
    op.drop_index('idx_automation_run_status', table_name='automation_runs')
    op.drop_index('idx_automation_run_started', table_name='automation_runs')
    op.drop_index('idx_automation_run_completed', table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index('idx_automation_config_key', table_name='automation_config')
    op.drop_table('automation_config')
    # ### end Alembic commands ###